spring.application.name=smartmall-backend

# Neon PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://ep-weathered-moon-aqwt4kdn-pooler.c-8.us-east-1.aws.neon.tech/smartmall?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_fWqI7y9NPsmw

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server
server.port=8080

# JWT
app.jwt.secret=smartmallx-dev-secret-key-change-in-production-1234567890
app.jwt.expiration-ms=86400000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html